version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.2.0
  aws-ecs: circleci/aws-ecs@02.2.1
jobs:
  test:
    docker:
      - image: circleci/node:14
        auth:
          username: sebi55
          password: $DOCKERHUB_PASSWORD
        environment:
          host: localhost
          username: admin
          password: passw0rd
          database: graphbook
          JWT_SECRET: 1234
      - image: circleci/mysql:8.0.4
        command: [--default-authentication-plugin=mysql_native_password]
        auth:
          username: sebi55
          password: $DOCKERHUB_PASSWORD
        environment:
          MYSQL_ROOT_PASSWORD: passw0rd
          MYSQL_DATABASE: graphbook
          MYSQL_USER: admin
          MYSQL_PASSWORD: passw0rd
    steps:
      - checkout
      - run: npm install
      - run:
          name: "Install Sequelize"
          command: sudo npm install -g mysql2 sequelize sequelize-cli
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: "Run migrations for test DB"
          command: sequelize db:migrate --migrations-path src/server/migrations --config src/server/config/index.js --env production
      - run:
          name: "Run tests"
          command: npm run test
          environment:
            NODE_ENV: production
workflows:
  build-and-deploy:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          repo: "graphbook"
          tag: "${CIRCLE_SHA1}"
          requires:
            - test
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
            - test
          family: "graphbook-task-definition"
          cluster-name: "graphbook-cluster"
          service-name: "graphbook-service"
          container-image-name-updates: "container=graphbook-container,tag=${CIRCLE_SHA1}"